import sys
from app.schemas.copilot import CopilotBriefingRequest, PredictionData, FeatureContribution, ResourcePlanData, DiversionPlanData, EventMetadataData
from app.services.traffic_commander import generate_executive_briefing, generate_fallback_briefing

def create_mock_request(impact: str, confidence: float, officers: int, corridor: bool) -> CopilotBriefingRequest:
    return CopilotBriefingRequest(
        prediction=PredictionData(impact_level=impact, confidence=confidence),
        feature_contributions=[
            FeatureContribution(feature="rush_hour", contribution=15.0),
            FeatureContribution(feature="road_closure", contribution=25.0)
        ],
        resource_plan=ResourcePlanData(
            deployment_score=78.5,
            officers_required=officers,
            patrol_vehicles=4,
            barricades=10,
            diversion_level="Major" if impact in ["High", "Critical"] else "Minor",
            emergency_corridor_required=corridor,
            estimated_response_time="12 mins",
            estimated_operational_cost=1500.00
        ),
        diversion_plan=DiversionPlanData(
            routes=[{"id": "primary", "name": "Route B", "recommended": True}],
            estimated_vehicles_diverted=350,
            estimated_delay_reduction="42%"
        ),
        event_metadata=EventMetadataData(
            event_type="planned",
            event_cause="political_rally",
            zone="South",
            junction="silk-board",
            attendance=15000,
            duration=3.5,
            start_time="17:00"
        )
    )

def main():
    print("Starting direct service testing...")
    req = create_mock_request("High", 92.0, 24, True)
    
    print("\n--- Testing Rule-Based Fallback Briefing ---")
    fallback_res = generate_fallback_briefing(req)
    print(f"Generated By: {fallback_res.generated_by}")
    print(f"Summary: {fallback_res.summary}")
    print(f"Risks: {fallback_res.risks}")
    print(f"Actions: {fallback_res.actions}")
    print(f"Commissioner Briefing: {fallback_res.commissioner_briefing}")
    print(f"Citizen Advisory: {fallback_res.citizen_advisory}")
    
    assert fallback_res.generated_by == "fallback"
    assert len(fallback_res.risks) >= 3
    assert len(fallback_res.actions) >= 3
    
    print("\n--- Testing Gemini Briefing (May fallback if key is invalid/fails) ---")
    gemini_res = generate_executive_briefing(req)
    print(f"Generated By: {gemini_res.generated_by}")
    print(f"Summary: {gemini_res.summary}")
    print(f"Risks: {gemini_res.risks}")
    print(f"Actions: {gemini_res.actions}")
    print(f"Commissioner Briefing: {gemini_res.commissioner_briefing}")
    print(f"Citizen Advisory: {gemini_res.citizen_advisory}")
    
    print("\n✅ Direct service tests passed successfully!")

if __name__ == "__main__":
    main()
