import json
import sys
from fastapi.testclient import TestClient

from app.main import app
from app.schemas.copilot import CopilotBriefingRequest, PredictionData, FeatureContribution, ResourcePlanData, DiversionPlanData, EventMetadataData
from app.services.traffic_commander import generate_executive_briefing, generate_fallback_briefing

client = TestClient(app)

# Helper mock data generator
def create_mock_request(impact: str, confidence: float, officers: int, corridor: bool) -> CopilotBriefingRequest:
    return CopilotBriefingRequest(
        prediction=PredictionData(impact_level=impact, confidence=confidence),
        feature_contributions=[
            FeatureContribution(feature="rush_hour", contribution=15.0),
            FeatureContribution(feature="road_closure", contribution=25.0)
        ],
        resource_plan=ResourcePlanData(
            deployment_score=78.5,
            officers_required=officers,
            patrol_vehicles=4,
            barricades=10,
            diversion_level="Major" if impact in ["High", "Critical"] else "Minor",
            emergency_corridor_required=corridor,
            estimated_response_time="12 mins",
            estimated_operational_cost=1500.00
        ),
        diversion_plan=DiversionPlanData(
            routes=[{"id": "primary", "name": "Route B", "recommended": True}],
            estimated_vehicles_diverted=350,
            estimated_delay_reduction="42%"
        ),
        event_metadata=EventMetadataData(
            event_type="planned",
            event_cause="political_rally",
            zone="South",
            junction="silk-board",
            attendance=15000,
            duration=3.5,
            start_time="17:00"
        )
    )

def test_impact_level(impact: str, confidence: float, officers: int, corridor: bool):
    print(f"\n==================================================")
    print(f"TESTING IMPACT LEVEL: {impact}")
    print(f"==================================================")
    req = create_mock_request(impact, confidence, officers, corridor)
    
    # 1. Test Fallback generator directly
    print("\n[Testing Fallback Service Directly]")
    fallback_res = generate_fallback_briefing(req)
    print(f"Generated By: {fallback_res.generated_by}")
    print(f"Summary: {fallback_res.summary}")
    print(f"Risks ({len(fallback_res.risks)}): {fallback_res.risks}")
    print(f"Actions ({len(fallback_res.actions)}): {fallback_res.actions}")
    print(f"Commissioner: {fallback_res.commissioner_briefing}")
    print(f"Citizen: {fallback_res.citizen_advisory}")
    
    assert len(fallback_res.risks) >= 3, "Should have at least 3 risks"
    assert len(fallback_res.actions) >= 3, "Should have at least 3 actions"
    assert fallback_res.generated_by == "fallback"

    # 2. Test Gemini generator directly (will fall back if key invalid/unavailable)
    print("\n[Testing Gemini Service Directly]")
    gemini_res = generate_executive_briefing(req)
    print(f"Generated By: {gemini_res.generated_by}")
    print(f"Summary: {gemini_res.summary}")
    print(f"Risks ({len(gemini_res.risks)}): {gemini_res.risks}")
    print(f"Actions ({len(gemini_res.actions)}): {gemini_res.actions}")
    print(f"Commissioner: {gemini_res.commissioner_briefing}")
    print(f"Citizen: {gemini_res.citizen_advisory}")

    # 3. Test API Route via TestClient
    print("\n[Testing FastAPI Router POST /api/copilot/briefing]")
    resp = client.post("/api/copilot/briefing", json=req.dict())
    assert resp.status_code == 200, f"API failed with {resp.status_code}: {resp.text}"
    api_data = resp.json()
    print(f"API Generated By: {api_data['generated_by']}")
    print(f"API Summary: {api_data['summary']}")
    assert "summary" in api_data
    assert "risks" in api_data
    assert "actions" in api_data

if __name__ == "__main__":
    try:
        test_impact_level("Low", 82.0, 4, False)
        test_impact_level("Medium", 88.0, 12, False)
        test_impact_level("High", 91.0, 24, True)
        test_impact_level("Critical", 95.0, 36, True)
        print("\n🎉 ALL TESTS PASSED SUCCESSFULLY!")
    except Exception as e:
        print(f"\n❌ TEST RUN ENCOUNTERED ERROR: {e}")
        sys.exit(1)
