"use client";

import React, { useState } from "react";
import { 
  Terminal, 
  AlertTriangle, 
  ShieldCheck, 
  RefreshCw, 
  ChevronDown, 
  ChevronUp, 
  Sparkles, 
  UserCheck, 
  Megaphone,
  Clock,
  Cpu
} from "lucide-react";
import { CopilotBriefing } from "@/store/useMLStore";

interface TrafficCommanderCardProps {
  briefing: CopilotBriefing | null;
  isGenerating: boolean;
  onRegenerate: () => void;
}

export function TrafficCommanderCard({ briefing, isGenerating, onRegenerate }: TrafficCommanderCardProps) {
  const [isOpen, setIsOpen] = useState(true);
  const [showCommissioner, setShowCommissioner] = useState(false);
  const [showCitizen, setShowCitizen] = useState(false);

  if (isGenerating) {
    return (
      <div className="rounded-xl border border-blue-500/30 bg-[#090d16] p-6 text-center animate-pulse flex flex-col items-center justify-center min-h-[220px]">
        <div className="relative flex items-center justify-center mb-4">
          <div className="absolute h-12 w-12 rounded-full border border-blue-500/20 animate-ping" />
          <div className="h-8 w-8 rounded-full border-2 border-blue-500 border-t-transparent animate-spin" />
        </div>
        <h4 className="font-mono text-xs uppercase tracking-wider text-blue-400">AI Traffic Commander</h4>
        <p className="text-[11px] text-slate-400 mt-2 max-w-[280px]">
          Synthesizing ML models, diversion routing matrices, and emergency hospital access lines into executive brief...
        </p>
      </div>
    );
  }

  if (!briefing) {
    return (
      <div className="rounded-xl border border-dashed border-white/10 bg-panel/30 p-6 text-center flex flex-col items-center justify-center min-h-[220px]">
        <Sparkles className="h-8 w-8 text-blue-500/50 mb-2 animate-pulse" />
        <h4 className="font-semibold text-slate-300 text-xs mb-1 uppercase tracking-wider">AI Traffic Commander Standby</h4>
        <p className="text-[10px] text-slate-500 max-w-[250px] mx-auto leading-relaxed mb-4">
          Generate an executive briefing translating complex ML prediction datasets into actionable deployment summaries.
        </p>
        <button
          onClick={onRegenerate}
          className="flex items-center gap-1.5 px-3 py-1.5 bg-blue-600 hover:bg-blue-500 text-white rounded text-xs font-bold transition shadow-[0_0_15px_rgba(37,99,235,0.2)]"
        >
          <RefreshCw className="h-3 w-3" /> Initialize Briefing
        </button>
      </div>
    );
  }

  const { summary, risks, actions, confidence, generated_by, timestamp, commissioner_briefing, citizen_advisory } = briefing;

  return (
    <div className="rounded-xl border border-white/10 bg-[#070b12] text-slate-200 overflow-hidden shadow-2xl flex flex-col transition duration-300 hover:border-blue-500/30">
      
      {/* Header */}
      <div className="flex items-center justify-between border-b border-white/10 bg-gradient-to-r from-slate-900 via-[#0a1220] to-slate-900 px-4 py-3">
        <div className="flex items-center gap-2">
          <Terminal className="h-4 w-4 text-blue-400" />
          <div>
            <h3 className="text-xs font-mono font-bold tracking-wider uppercase text-slate-100 flex items-center gap-1.5">
              AI Traffic Commander <span className="text-[9px] text-blue-400 font-semibold lowercase">v1.2</span>
            </h3>
            <p className="text-[9px] text-slate-500 font-mono">Executive Briefing Layer</p>
          </div>
        </div>

        <div className="flex items-center gap-3">
          {/* Generated By Tag */}
          <span className={`px-2 py-0.5 rounded text-[8px] font-mono font-bold border uppercase tracking-wider ${
            generated_by === "gemini" 
              ? "bg-purple-500/10 text-purple-400 border-purple-500/20 shadow-[0_0_10px_rgba(168,85,247,0.1)]" 
              : "bg-amber-500/10 text-amber-400 border-amber-500/20"
          }`}>
            {generated_by} mode
          </span>

          {/* Action buttons */}
          <button 
            onClick={onRegenerate}
            disabled={isGenerating}
            title="Regenerate Executive Briefing"
            className="p-1 rounded bg-white/5 border border-white/10 text-slate-400 hover:text-white hover:bg-white/10 transition"
          >
            <RefreshCw className="h-3 w-3" />
          </button>
          
          <button 
            onClick={() => setIsOpen(!isOpen)}
            className="p-1 rounded bg-white/5 border border-white/10 text-slate-400 hover:text-white hover:bg-white/10 transition"
          >
            {isOpen ? <ChevronUp className="h-3 w-3" /> : <ChevronDown className="h-3 w-3" />}
          </button>
        </div>
      </div>

      {/* Main Content */}
      {isOpen && (
        <div className="p-4 flex flex-col gap-4 animate-fadeIn">
          
          {/* Executive Summary */}
          <div className="bg-white/[0.02] border border-white/5 rounded-lg p-3.5">
            <h4 className="text-[10px] font-bold text-slate-400 uppercase tracking-widest mb-1.5 font-mono">Executive Summary</h4>
            <p className="text-xs text-slate-200 leading-relaxed font-sans font-medium">
              {summary}
            </p>
          </div>

          <div className="grid grid-cols-2 gap-4">
            {/* Operational Risks */}
            <div className="flex flex-col gap-2 bg-[#0d0707] border border-red-950/40 rounded-lg p-3.5">
              <h4 className="text-[10px] font-bold text-red-400 uppercase tracking-widest font-mono flex items-center gap-1.5 border-b border-red-950/60 pb-1.5 mb-1">
                <AlertTriangle className="h-3.5 w-3.5 text-red-500" /> Operational Risks
              </h4>
              <ul className="flex flex-col gap-2">
                {risks.map((risk, index) => (
                  <li key={index} className="flex gap-2 text-xs text-slate-300 font-sans leading-relaxed">
                    <span className="text-red-500 font-bold font-mono text-[10px] mt-[1.5px]">•</span>
                    <span>{risk}</span>
                  </li>
                ))}
              </ul>
            </div>

            {/* Recommended Actions */}
            <div className="flex flex-col gap-2 bg-[#070e0a] border border-emerald-950/40 rounded-lg p-3.5">
              <h4 className="text-[10px] font-bold text-emerald-400 uppercase tracking-widest font-mono flex items-center gap-1.5 border-b border-emerald-950/60 pb-1.5 mb-1">
                <ShieldCheck className="h-3.5 w-3.5 text-emerald-500" /> Recommended Actions
              </h4>
              <ul className="flex flex-col gap-2">
                {actions.map((action, index) => (
                  <li key={index} className="flex gap-2 text-xs text-slate-300 font-sans leading-relaxed">
                    <span className="text-emerald-500 font-bold font-mono text-[10px] mt-[1.5px]">✓</span>
                    <span>{action}</span>
                  </li>
                ))}
              </ul>
            </div>
          </div>

          {/* Collapsible Modes */}
          <div className="flex flex-col gap-2 border-t border-white/5 pt-3">
            
            {/* Commissioner Briefing Accordion */}
            {commissioner_briefing && (
              <div className="border border-white/5 rounded-md overflow-hidden bg-white/[0.01]">
                <button
                  type="button"
                  onClick={() => setShowCommissioner(!showCommissioner)}
                  className="w-full px-3 py-2 flex items-center justify-between text-xs font-semibold text-slate-300 hover:text-white hover:bg-white/5 transition font-mono"
                >
                  <span className="flex items-center gap-1.5">
                    <UserCheck className="h-3.5 w-3.5 text-blue-400" />
                    Commissioner Briefing Mode
                  </span>
                  {showCommissioner ? <ChevronUp className="h-3 w-3" /> : <ChevronDown className="h-3 w-3" />}
                </button>
                {showCommissioner && (
                  <div className="px-3 py-2.5 bg-black/20 border-t border-white/5 text-[11px] text-slate-400 leading-relaxed font-sans">
                    {commissioner_briefing}
                  </div>
                )}
              </div>
            )}

            {/* Citizen Advisory Accordion */}
            {citizen_advisory && (
              <div className="border border-white/5 rounded-md overflow-hidden bg-white/[0.01]">
                <button
                  type="button"
                  onClick={() => setShowCitizen(!showCitizen)}
                  className="w-full px-3 py-2 flex items-center justify-between text-xs font-semibold text-slate-300 hover:text-white hover:bg-white/5 transition font-mono"
                >
                  <span className="flex items-center gap-1.5">
                    <Megaphone className="h-3.5 w-3.5 text-emerald-400" />
                    Citizen Advisory Mode
                  </span>
                  {showCitizen ? <ChevronUp className="h-3 w-3" /> : <ChevronDown className="h-3 w-3" />}
                </button>
                {showCitizen && (
                  <div className="px-3 py-2.5 bg-black/20 border-t border-white/5 text-[11px] text-slate-400 leading-relaxed font-sans">
                    {citizen_advisory}
                  </div>
                )}
              </div>
            )}

          </div>

          {/* Footer Metadata */}
          <div className="border-t border-white/10 pt-2.5 mt-1 flex items-center justify-between text-[9px] text-slate-500 font-mono">
            <span className="flex items-center gap-1">
              <Clock className="h-3 w-3" /> Updated: {new Date(timestamp).toLocaleTimeString()}
            </span>
            <span className="flex items-center gap-1">
              <Cpu className="h-3 w-3 text-purple-400" /> Confidence: {Math.round(confidence)}%
            </span>
          </div>

        </div>
      )}

    </div>
  );
}
export default TrafficCommanderCard;
