"use client";

import { useEffect, useState, useMemo } from "react";
import { useAlertStore } from "@/store/useAlertStore";
import AlertCard from "./AlertCard";
import { ShieldAlert, BellOff, Loader2, ListFilter, Trash2 } from "lucide-react";

export function AlertsCenterView() {
  const { alerts, loading, error, fetchAlerts, dismissAlert } = useAlertStore();
  const [filter, setFilter] = useState<"all" | "high" | "medium">("all");

  useEffect(() => {
    fetchAlerts();
    const interval = setInterval(() => fetchAlerts(), 5000);
    return () => clearInterval(interval);
  }, [fetchAlerts]);

  // Filter alerts
  const filteredAlerts = useMemo(() => {
    return alerts.filter((a) => {
      if (filter === "high") return a.confidence >= 85;
      if (filter === "medium") return a.confidence >= 70 && a.confidence < 85;
      return true;
    });
  }, [alerts, filter]);

  // Bulk clear dismissals
  const dismissAllAlerts = async () => {
    if (alerts.length === 0) return;
    for (const a of alerts) {
      await dismissAlert(a.alert_id);
    }
  };

  return (
    <div className="flex flex-col gap-6 p-6 h-full overflow-y-auto bg-[#080808]">
      
      {/* Title & Actions */}
      <div className="flex justify-between items-center">
        <div>
          <h1 className="text-xl font-bold tracking-tight text-white flex items-center gap-2">
            Predictive Alert Center <ShieldAlert className="h-5 w-5 text-red-500 animate-pulse" />
          </h1>
          <p className="text-slate-400 text-xs mt-0.5">
            Active warning triggers generated by incident escalation, corridor blockages, and resource deficits.
          </p>
        </div>
        
        <div className="flex items-center gap-2">
          {alerts.length > 0 && (
            <button
              onClick={dismissAllAlerts}
              className="flex items-center gap-1.5 px-3 py-1.5 rounded-lg border border-red-500/20 bg-red-500/5 text-xs text-red-400 transition hover:bg-red-500/10 font-bold"
            >
              <Trash2 className="h-3.5 w-3.5" />
              <span>Dismiss All Warnings</span>
            </button>
          )}
        </div>
      </div>

      {/* Filter Tabs & Stats Bar */}
      <div className="flex justify-between items-center bg-panel border border-white/5 p-3 rounded-xl shadow-md">
        <div className="flex items-center gap-2 text-xs">
          <ListFilter className="h-4 w-4 text-slate-400" />
          <span className="font-semibold text-slate-400 mr-2">Filters:</span>
          
          <button
            onClick={() => setFilter("all")}
            className={`px-3 py-1 rounded-md transition ${
              filter === "all" ? "bg-blue-600/20 text-blue-400 border border-blue-500/25 font-bold" : "text-slate-400 hover:text-slate-200"
            }`}
          >
            All Alerts ({alerts.length})
          </button>

          <button
            onClick={() => setFilter("high")}
            className={`px-3 py-1 rounded-md transition ${
              filter === "high" ? "bg-red-600/20 text-red-400 border border-red-500/25 font-bold" : "text-slate-400 hover:text-slate-200"
            }`}
          >
            High Risk (85%+) ({alerts.filter((a) => a.confidence >= 85).length})
          </button>

          <button
            onClick={() => setFilter("medium")}
            className={`px-3 py-1 rounded-md transition ${
              filter === "medium" ? "bg-orange-600/20 text-orange-400 border border-orange-500/25 font-bold" : "text-slate-400 hover:text-slate-200"
            }`}
          >
            Moderate Risk (70-85%) ({alerts.filter((a) => a.confidence >= 70 && a.confidence < 85).length})
          </button>
        </div>

        <span className="text-[10px] font-mono text-slate-500">Auto-refreshing every 5s</span>
      </div>

      {/* Main Content Grid */}
      <div className="flex-1 min-h-0">
        {loading && alerts.length === 0 ? (
          <div className="flex h-48 flex-col items-center justify-center gap-3 text-slate-500">
            <Loader2 className="h-6 w-6 animate-spin text-blue-500" />
            <span className="text-xs">Processing warning signals...</span>
          </div>
        ) : error && alerts.length === 0 ? (
          <div className="rounded-xl border border-red-950 bg-red-950/20 p-6 text-center max-w-md mx-auto mt-8">
            <p className="text-sm text-red-400 font-semibold">{error}</p>
          </div>
        ) : filteredAlerts.length === 0 ? (
          <div className="flex flex-col items-center justify-center gap-3 rounded-xl border border-dashed border-white/10 bg-white/5 py-12 text-center max-w-lg mx-auto mt-6">
            <BellOff className="h-10 w-10 text-slate-600" />
            <h3 className="text-sm font-bold text-slate-300 uppercase tracking-wider">No Warnings Registered</h3>
            <p className="text-xs text-slate-500 max-w-[280px]">
              All junctions and corridors are performing within baseline thresholds.
            </p>
          </div>
        ) : (
          <div className="grid grid-cols-2 gap-4 overflow-y-auto max-h-[calc(100vh-280px)] pr-2">
            {filteredAlerts.map((alert) => (
              <AlertCard
                key={alert.alert_id}
                alert={alert}
                onDismiss={dismissAlert}
              />
            ))}
          </div>
        )}
      </div>
    </div>
  );
}
export default AlertsCenterView;
